### ISSUE TITLE
No ability to merge maps

### ISSUE THREAD

**Issue by psachs21** [loggur/provide-map#1]
I'd like to be able to provide a map and have it merged into the existing map (on a shallow level).

 I'm prepared to write a PR assuming it seems like a good idea and there isn't some other way to do this that I am missing.

**Comment by timbur** [comment]
Sounds interesting.  Can you provide an example of what exactly you're wanting to do?

**Comment by psachs21** [comment]
Basically I want a map that is being used to list a bunch of items that can be updated by either adding items to the list of modifying existing ones. At some point I'll want removal but I'm not there yet.

```
initialMap = {
  1: { name: 'a' },
  2: { name: 'b' },
  3: { name: 'c' }
}

updates = {
  1: { name: 'new a' },
  4: { name: 'd' }
}

desiredResult = {
  1: { name: 'new a'},
  2: { name: 'b' },
  3: { name: 'c' },
  4: { name: 'd' }
}
```

**Comment by psachs21** [comment]
According to [this](http://stackoverflow.com/questions/32000865/simplest-way-to-merge-es6-maps-sets) merging of maps can be done like this: 

```
 new Map([...map1, ...map2, ...map3])
```

but that doesn't do what I expected. I could iterate and do it manually, but i figured there was a cleaner way to do it with deconstruction... somehow.
