### ISSUE TITLE
Standard Api for provider exports?

### ISSUE THREAD

**Issue by SeeThruHead** [loggur/provide-map#3]
I've having a lot of trouble with the fact that constants are spread when exporting providers.

1. It seems out of place when everything else has a predictable key.
2. Exporting as 'actionTypes' would give all providers a base signature we can rely on.
3. It screws with named imports 

example, i'd like to combine two providers together into one, i now need to spread the action types from two providers into one object, rather than spread the actionTypes from both objects into one combined actionTypes object the is exported by name.

With the export one object you can no longer to things like 
```
import { reducers, actions } from './some-provider'
````

which is annoying when i'd like to respond to one providers actions inside a saga for example

**Comment by timbur** [comment]
You make a good point.  The reason I originally did it like that was to help enforce the fact that constants should almost never be used outside of a provider.  Although I can see it being necessary when using something like `provide-map` where you'll want to extend it and/or use it to compose another provider, which is why they're included on the created provider object.

Other than that, I've never encountered the need to import action types from other providers, and if/when it crossed my mind, I took it as a sign of bad design and went with a different approach (usually using components as the "glue" between providers) which ultimately works out for the best in the end.  But I have no qualms with putting action types into their own object if that's what people want.

You can also export/import the providers however you want.  But the reason I've always exported as default single objects is for the same reason above, where you want each provider to be as encapsulated as possible - i.e., you should never actually have the need to import reducers, actions, constants, etc., elsewhere.

That said, I am always open to improvement, especially if an argument or a real world example is compelling enough to warrant change.

**Comment by SeeThruHead** [comment]
It's really only an issue when I'm extending providers with actions that need to be fired from sagas. Where you might be using components to glue providers together i **only** use sagas to talk between providers (all actions fired by components go to a saga, which will be the place provider actions are fired from) unfortunately sagas do not get provider actions injected into them like components do, so i need to import them explicitly. It's nice to be able to do named imports for this reason. But we cannot do named imports if we are only exporting an object as default (this used to be possible in babel 5 but it's not part of the es6 spec and no longer works)

So to accomplish this I can manually destructure all constant from provide-map and export them as an actionTypes object, though it would be a little nicer if they came that way.

ie:
```
// some-provider
export const actionTypes = {
  ACTION_ONE: 'ACTION_ONE',
  ACTION_TWO: 'ACTION_TWO
};

export const actions = { ... };
export const reducers = { ... };
export const merge = { ... };

export default { actionTypes, actions, reducers, merge };

**Comment by timbur** [comment]
That looks like a pretty solid design and it seems like it would work for your particular needs.  I'm confused now about the real problem here.  With provider factories (like `provide-map`), since it's a function that returns a provider, there's no way to structure the exports like that unless you do this:
```js
// src/providers/someMap.js

import provideMap from 'provide-map';

const someMap = provideMap('someMap', 'someItem', 'someIndex');
const { actions, reducers, merge } = someMap;

export { actions, reducers, merge };
export default someMap;
```

**Comment by SeeThruHead** [comment]
yeah for provider factories we have this limitation of course and would need to name export ourselves

if you look at provide-page there is another example where we could use named exports for everything
and export altogether as default

that way if i ever need to extend provide page, or fire it's actions from a saga (very likely) i could use named imports

**Comment by timbur** [comment]
I think Babel 6's "loose" mode will give you the functionality you want without any extra code.  But yeah it would be nice to have everything working the way you want within the standard.  Let me think about it some more and I'll take a closer look at sagas and see if there might actually be a better way.

Regarding `provide-page`, this is how I'm using it to compose it (and `provide-map`) into the `entries` provider for the next version of `bloggur` that will use v6.0 of `react-redux-provide`.  It's currently untested but should work, in theory:
```js
import provideMap from 'provide-map';
import providePage from 'provide-page';
import { PUSH_WINDOW_PATH, REPLACE_WINDOW_PATH } from 'provide-page';

const entries = provideMap('entries', 'entry', 'entryKey');

const { SET_ENTRY, UPDATE_ENTRY, DELETE_ENTRY } = entries;
const SELECT_ENTRY = 'SELECT_ENTRY';
const CREATE_ENTRY = 'CREATE_ENTRY';
const EDIT_ENTRY = 'EDIT_ENTRY';

function normalizeEntry(entry) {
  const { contents = '' } = entry;

  const name = entry.name || contents
    .split('\n')
    .shift()
    .replace(/^#/, '')
    .trim();

  const href = entry.href || name
    .toLowerCase()
    .replace(/[^a-z0-9 ]/gi, '')
    .trim()
    .replace(/ /gi, '-');

  return { ...entry, name, href };
}

Object.assign(entries.actions, providePage.actions, {
  selectEntry(entryKey) {
    return { type: SELECT_ENTRY, entryKey };
  },

  createEntry() {
    return { type: CREATE_ENTRY };
  },

  editEntry() {
    return { type: EDIT_ENTRY };
  },

  setEntry(entryKey, entry) {
    entry = normalizeEntry(entry);
    entryKey = entryKey || entry.href;
    return { type: SET_ENTRY, entryKey, entry };
  },

  updateEntry(entryKey, entry) {
    entry = normalizeEntry(entry);
    entryKey = entryKey || entry.href;
    return { type: UPDATE_ENTRY, entryKey, entry };
  }
});

Object.assign(entries.reducers, providePage.reducers, {
  selectedEntryKey(state = null, action) {
    switch (action.type) {
      case CREATE_ENTRY:
      case DELETE_ENTRY:
        return null;

      case SELECT_ENTRY:
        return action.entryKey || null;

      case PUSH_WINDOW_PATH:
      case REPLACE_WINDOW_PATH:
        return action.windowPathSplit[0] || null;

      default:
        return state;
    }
  },

  creatingEntry(state = 0, action) {
    switch (action.type) {
      case CREATE_ENTRY:
        return state || new Date().getTime();

      case PUSH_WINDOW_PATH:
      case REPLACE_WINDOW_PATH:
        return action.windowPathSplit[0] === 'create'
          ? state || new Date().getTime()
          : 0;

      default:
        return state;
    }
  },

  editingEntry(state = false, action) {
    switch (action.type) {
      case EDIT_ENTRY:
        return true;

      case PUSH_WINDOW_PATH:
      case REPLACE_WINDOW_PATH:
        return action.windowPathSplit[1] === 'edit';

      default:
        return state;
    }
  },

  deletedEntry(state = false, action) {
    switch (action.type) {
      case DELETE_ENTRY:
        return true;

      default:
        return false;
    }
  }
});

entries.merge.selectedEntry = {
  keys: ['entries', 'selectedEntryKey'],
  get({ entries, selectedEntryKey }) {
    return entries && entries.get(selectedEntryKey) || null;
  }
};

entries.merge.isSelectedEntry = {
  keys: ['selectedEntryKey'],
  get({ selectedEntryKey }, { entryKey }) {
    return selectedEntryKey === entryKey;
  }
};

export default entries;
```

**Comment by SeeThruHead** [comment]
This might actually work out for me after closer inspection, I'll give it a shot tmrw and report back. I do think there is likely a better way once we can figure out how to make saga middleware a supported paradigm in provider-world. Thanks again.
